### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by faddat**
# Documentation

## Description

This is an updated readme.md file for v-systems which should provide a warm welcome to our community members.  It also begins a migration of documentation out of the Wiki and into versioned markdown files that users will clone when they download VSYS software.  

## Motivation and Context

This makes our repository a more attractive, friendlier place to visit.  

## How Has This Been Tested

Reading and reading and re-reading, and re-drafting and re-organizing to the point of silliness.  It's now about ready for prime time, I think.  

## Types of changes

- [x ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by faddat** [comment]
Hmmmmmmmm.  Please correct me if I'm wrong:

1) We have documentation in the Wiki
2) We've got documentation Here:  https://github.com/virtualeconomy/document

Anywhere else?  

## My thinking is like this:  

We can put our docs alongside our code so that they are cloned with the code.  Additionally, this "v-systems" repository can become a "single source of truth" and our versioning will be consistent on documentation and code.  

To make a long story short, I'd like to get our code and its documentation in the same place to make things easier on users :).

**Comment by faddat** [comment]
Also, clearly I'll need to amend the PR and this one shouldn't be merged.  

Need to sort out which set of docs is canonical-- the Wiki or https://github.com/virtualeconomy/document ?

Thanks!

**Comment by faddat** [comment]
Ah, while we are on this topic, I see that we currently have a "howto" repo.  In order to increase our appeal to developers, I'd like to get those docs either under /documentation or /howto in this repository.  

I'll open an issue about all this jibber-jabber :).

**Comment by ncying** [comment]
It is better to re-organized the wiki rather than merged the documentation directly in source code.

**Pull request closed without merging**
