### PR TITLE
multi-architecture support

### PR DESCRIPTION
**Pull request by faddat**
# PR Details

Enables aarch64 support

#167 
## Motivation and Context

Phones and Pi's now support vsys

## How Has This Been Tested

rpi 4 and pinephone

## Types of changes

-   [ ]   Docs change / refactoring / dependency upgrade
-   [ ]   Bug fix (non-breaking change which fixes an issue)
-   [x]   New feature (non-breaking change which adds functionality)
-   [ ]   Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x]   My code follows the code style of this project.
-   [ ]   My change requires a change to the documentation.
-   [ ]   I have updated the documentation accordingly.
-   [ ]   I have added tests to cover my changes.
-   [x]   All new and existing tests passed.

### CODE REVIEW

**Review by ncying — CHANGES_REQUESTED** [review]
#167 we need seriously check and package updates. We can not directly cite some 3rd party dependency directly since everyone can upload their complied package to mvn-repo.  I already noticed many related packages listed. But for some security problems, we still keep the original dependency first, since this support is not necessary for all devices.

And you should also need to test this update work or not. Build the jar package and run the node on an Android phone or Raspberry Pi.

**Comment by faddat** [comment]
I think that I've chosen this package from a well-audited source, but if you have thoughts on another, please let me know.

**Comment by ncying** [comment]
@faddat you should also check that package based on this new dependency can be will start in the aarch64 device.

**Comment by faddat** [comment]
Screen Shot 2020-09-09 at 12 34 45 PM

So, seems I made it explode.  Maybe library compatibility, I'll fiddle with it and see what I can do.  

do you have a good document that explains scala compilation?  I'd like to refactor our build system to use mill, but that did not go so great for me so far.

**Comment by faddat** [comment]
Screen Shot 2020-09-09 at 2 31 00 PM
Screen Shot 2020-09-09 at 2 32 46 PM

**Comment by faddat** [comment]
It even compiles on raspberry pie and pine phone, but there is the problem
with the old node preventing easy sync.

**Comment by faddat** [comment]
So I have reviewed this to the best of my knowledge. I do not think that it introduces any kind of security risk. 

If we merge it, we gain hardware build targets for VSYS software.

**Pull request closed without merging**
