### PR TITLE
Contract last token API

### PR DESCRIPTION
**Pull request by ncying**
# PR Details

## Description

Add contract last token API
Remove contract data API key request

## Related Issue

None

## How Has This Been Tested

All unit test passed

## Types of changes

-   [x]   New feature (non-breaking change which adds functionality)

## Checklist

-   [x]   My code follows the code style of this project.
-   [x]   All new and existing tests passed.

### CODE REVIEW

**Comment by SheldonYS** [comment]
API seems not found. When I call the /contract/lastTokenIndex/{contractId} ( for instance, http://test.v.systems:9922/contract/lastTokenIndex/CF5Tz9U9ytxw7H1vQxxLJhsYEmd7NJsk2QN ), the get response with "The requested resource could not be found but may be available again in the future."

**Comment by ncying** [comment]
> API seems not found. When I call the /contract/lastTokenIndex/{contractId} ( for instance, http://test.v.systems:9922/contract/lastTokenIndex/CF5Tz9U9ytxw7H1vQxxLJhsYEmd7NJsk2QN ), the get response with "The requested resource could not be found but may be available again in the future."

add to path prefix in https://github.com/virtualeconomy/v-systems/pull/251/commits/b77ef532f209e8fd26f72f56d7ed1fbbbe6113da

**Review by Icermli — APPROVED** [review]

**Comment by SheldonYS** [comment]
We'd better remove `authorizations = Array(new Authorization("api_key"))` at Line 105 in `src/main/scala/vsys/api/http/contract/ContractApiRoute.scala`. Or there is lock icon in Swagger for `​/contract​/data​/{contractId}​/{key}` API (though no need API Key).

Screenshot 2021-01-06 at 2 32 43 PM

**Comment by ncying** [comment]
> We'd better remove `authorizations = Array(new Authorization("api_key"))` at Line 105 in `src/main/scala/vsys/api/http/contract/ContractApiRoute.scala`. Or there is lock icon in Swagger for `​/contract​/data​/{contractId}​/{key}` API (though no need API Key).
> 
> Screenshot 2021-01-06 at 2 32 43 PM

Resolved in
https://github.com/virtualeconomy/v-systems/pull/256

**Comment by SheldonYS** [comment]
It seems the `lastTokenIndex` API not actually show the index of last existed token. For instance, 
* when I just register a NFT contract without issue any NFT, the API returns index=0
* If I issue a NFT which index=0, then calling this API returns index=1
......
Maybe we'd better rename it `nextTokenIndex` or `tokenCount`.

**Pull request merged**
